import { Pool, Lawyer, Auction } from '@/types';

export const mockLawyers: Lawyer[] = [
  {
    id: '1',
    name: 'Rebecca L. Martinez',
    address: '0x1a2B...8f9E',
    successFee: 0.15,
    rating: 4.9,
    casesWon: 42,
    specialization: 'Tax Fraud & IRS Whistleblower Law',
    bio: 'Former IRS Senior Attorney with 15+ years experience. Specialized in Form 211 filings and large-scale tax fraud cases. Successfully recovered over $2.3B in awards.',
    barAdmissions: ['CA', 'NY', 'DC'],
    notableCases: [
      'UBS Swiss Account Case ($780M award)',
      'Credit Suisse Tax Evasion ($260M award)',
      'FCPA Tax Violations ($450M settlement)',
    ],
  },
  {
    id: '2',
    name: 'David S. Kim',
    address: '0x7c9e...3d2A',
    successFee: 0.18,
    rating: 4.8,
    casesWon: 38,
    specialization: 'Cryptocurrency & Digital Asset Tax Law',
    bio: 'Leading expert in crypto tax compliance and IRS regulations. Represented in major digital asset cases including exchange audits and DeFi protocol compliance.',
    barAdmissions: ['TX', 'FL', 'DE'],
    notableCases: [
      'Coinbase Audit Defense ($12M settlement)',
      'BitMEX Compliance Review',
      'Terra Luna Tax Investigation ($89M)',
    ],
  },
  {
    id: '3',
    name: 'Amanda C. Foster',
    address: '0x5f8B...1e7C',
    successFee: 0.20,
    rating: 4.7,
    casesWon: 29,
    specialization: 'Corporate Whistleblowing & SEC Cases',
    bio: 'Specializes in corporate fraud and securities violations. Former SEC enforcement attorney with deep expertise in qui tam litigation and Dodd-Frank whistleblower protections.',
    barAdmissions: ['NY', 'MA', 'CT'],
    notableCases: [
      'Enron-Style Accounting Fraud ($1.2B recovery)',
      'Healthcare Fraud Scheme ($340M settlement)',
      'Pharmaceutical Kickback Case ($280M)',
    ],
  },
  {
    id: '4',
    name: 'James T. O\'Brien',
    address: '0x9d3A...6f8B',
    successFee: 0.17,
    rating: 4.6,
    casesWon: 35,
    specialization: 'International Tax & Offshore Compliance',
    bio: 'International tax attorney focused on FBAR violations and offshore tax evasion. Expert in FATCA compliance and cross-border tax matters.',
    barAdmissions: ['FL', 'NV', 'WA'],
    notableCases: [
      'Swiss Bank Compliance Program',
      'Panama Papers Investigation',
      'Foreign Trust Tax Evasion ($156M)',
    ],
  },
  {
    id: '5',
    name: 'Maria Elena Gonzalez',
    address: '0x2e7D...4b2A',
    successFee: 0.16,
    rating: 4.9,
    casesWon: 31,
    specialization: 'Payroll Fraud & Employment Tax',
    bio: 'Employment tax specialist with focus on worker misclassification and payroll tax fraud. Represented clients in complex multi-state payroll audits.',
    barAdmissions: ['CA', 'AZ', 'NM'],
    notableCases: [
      'Gig Economy Worker Misclassification',
      'Payroll Tax Fraud Ring ($67M)',
      'Contractor vs Employee Classification',
    ],
  },
];

export const mockPools: Pool[] = [
  {
    id: '1',
    name: 'FraudCorp Tax Evasion',
    description: 'Evidence of systematic tax avoidance practices',
    creator: '0xanonymous',
    shards: [],
    strength: 0,
    threshold: 75,
    status: 'active',
    createdAt: Date.now() - 86400000,
  },
  {
    id: '2',
    name: 'Shell Company Network',
    description: 'Offshore shell company schemes',
    creator: '0xanonymous',
    shards: [],
    strength: 0,
    threshold: 80,
    status: 'active',
    createdAt: Date.now() - 172800000,
  },
  {
    id: '3',
    name: 'Payroll Fraud Scheme',
    description: 'Misclassification of employees',
    creator: '0xanonymous',
    shards: [],
    strength: 0,
    threshold: 70,
    status: 'active',
    createdAt: Date.now() - 259200000,
  },
];

export const mockAuctions: Auction[] = [];